# Generated by Django 4.0.1 on 2022-01-14 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=120)),
                ('surnames', models.CharField(max_length=120)),
                ('image', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('summary', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('nacionality', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('apitude', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PERSON',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initDate', models.DateField()),
                ('endDate', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='chiback.person')),
            ],
            options={
                'db_table': 'EXPERIENCE',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=150)),
                ('initDate', models.DateField()),
                ('endDate', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educationList', to='chiback.person')),
            ],
            options={
                'db_table': 'EDUCATION',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('initDate', models.DateField()),
                ('endDate', models.DateField()),
                ('idCredential', models.CharField(max_length=200)),
                ('linkCredential', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='chiback.person')),
            ],
            options={
                'db_table': 'CERTIFICATE',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeAch', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='chiback.person')),
            ],
            options={
                'db_table': 'ACHIEVEMENT',
            },
        ),
    ]
